# Generated by Django 6.0.5 on 2026-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='full_portrait_url',
            field=models.URLField(blank=True),
        ),
    ]
