# Generated by Django on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_map_weapon_riotaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='modes',
            field=models.ManyToManyField(blank=True, related_name='maps', to='agents.mode'),
        ),
    ]
