# Generated by Django on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_map_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='magazine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='fire_rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
