# Generated by Django on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_weapon_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='damage_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='max_range_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='run_speed_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='firing_modes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
