# Generated by Django on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_weapon_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='wall_penetration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='equip_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='reload_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='ads_zoom_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
